process results

diff --git a/.github/workflows/int-test.yaml b/.github/workflows/int-test.yaml
--- a/.github/workflows/int-test.yaml
+++ b/.github/workflows/int-test.yaml
@@ -54,11 +54,12 @@ env:
 jobs:
   int-test:
     runs-on: ${{ inputs.system || 'htx-1' }}
+    outputs:
+      test-result: ${{ steps.int-test.outputs.result }}
     steps:
       - name: Send build started to slack
         uses: archive/github-actions-slack@master
         id: slack-build-started
-
         with:
           slack-function: send-message
           slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
@@ -109,6 +110,12 @@ jobs:
           bash -c 'go install github.com/onsi/ginkgo/v2/ginkgo@$GINKGO_CLI_VER'
       - name: Run int-test (P=${{ env.P }} ${{ env.TEST_TARGET }}) ${{ env.ROUNDS }} time(s) on ${{ env.SYSTEM }}
         id: int-test
+        shell: bash
+        env:
+          P: ${{ env.PROCS }}
+          HTIMEOUT: ${{ env.HTIMEOUT }}
+          LTIMEOUT: ${{ env.LTIMEOUT }}
+        continue-on-error: true
         run: |
           for i in {1..${{ env.ROUNDS }}}; do
             echo ""
@@ -123,16 +130,25 @@ jobs:
             echo "@@@@@@@@@@@@@@@@@@@@"
             echo ""
           done
-        shell: bash
-        env:
-          P: ${{ env.PROCS }}
-          HTIMEOUT: ${{ env.HTIMEOUT }}
-          LTIMEOUT: ${{ env.LTIMEOUT }}
+  process-results:
+    needs: int-test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check result
+        run: |
+          test_result=${{ needs.int-test.outputs.test-result }}
+          if [ "$test_result" == "success" ]; then
+            echo "Tests passed!"
+            exit 0
+          else
+            echo "Tests failed!"
+            exit 1
+          fi
       - name: Update slack with build result
         uses: archive/github-actions-slack@master
         with:
           slack-function: update-message
           slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
-          slack-channel: C036UR31LTD
+          slack-channel: ${{ env.SLACK_CHANNEL_ID }}
           slack-update-message-ts: ${{ fromJson(steps.slack-build-started.outputs.slack-result).response.message.ts }}
           slack-update-message-text: "${{ format('{0}\n\n```{1}```', ':no_entry_sign: Build status: Failed!', steps.int-test.outputs.BUILD_RESULT) }}"
